"""empty message

Revision ID: 2714485b741d
Revises: 2120992ba9cb
Create Date: 2014-03-08 20:22:44.373400

"""

# revision identifiers, used by Alembic.
revision = '2714485b741d'
down_revision = '2120992ba9cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('semifinalist', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'semifinalist')
    ### end Alembic commands ###
