"""empty message

Revision ID: 36ea9b738d26
Revises: 185eb614137e
Create Date: 2014-03-27 07:22:14.042788

"""

# revision identifiers, used by Alembic.
revision = '36ea9b738d26'
down_revision = '185eb614137e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secondroundjudging',
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.create_table('second_round_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('presentation', sa.Float(), nullable=True),
    sa.Column('innovation', sa.Float(), nullable=True),
    sa.Column('plan', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('weighted', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'judge', sa.Column('semifinalistjudge', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'judge', 'semifinalistjudge')
    op.drop_table('second_round_score')
    op.drop_table('secondroundjudging')
    ### end Alembic commands ###
