"""empty message

Revision ID: 4889a3e9dac5
Revises: eafc16ddeb9
Create Date: 2014-03-30 18:01:30.054343

"""

# revision identifiers, used by Alembic.
revision = '4889a3e9dac5'
down_revision = 'eafc16ddeb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('finalpresentation', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'finalpresentation')
    ### end Alembic commands ###
