"""empty message

Revision ID: 585ea74546fa
Revises: e7b4fcdc65e
Create Date: 2014-03-28 00:53:26.080830

"""

# revision identifiers, used by Alembic.
revision = '585ea74546fa'
down_revision = 'e7b4fcdc65e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
