"""empty message

Revision ID: 93d2915723e
Revises: 36ea9b738d26
Create Date: 2014-03-28 00:51:15.413672

"""

# revision identifiers, used by Alembic.
revision = '93d2915723e'
down_revision = '36ea9b738d26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
