"""empty message

Revision ID: a8dc2db25c4
Revises: c687d53a10c
Create Date: 2016-01-03 22:25:52.850191

"""

# revision identifiers, used by Alembic.
revision = 'a8dc2db25c4'
down_revision = 'c687d53a10c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('active', mysql.TINYINT(display_width=1), nullable=True))
    ### end Alembic commands ###
