"""empty message

Revision ID: bfb04f92eba
Revises: None
Create Date: 2014-02-02 02:09:04.147697

"""

# revision identifiers, used by Alembic.
revision = 'bfb04f92eba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projectname', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('phaseone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pwdhash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sponsor_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('prize', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectname', sa.String(length=100), nullable=True),
    sa.Column('info', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('weighted', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pwdhash', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('judging',
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.create_table('schools',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    op.drop_table('judging')
    op.drop_table('member')
    op.drop_table('score')
    op.drop_table('past_winner')
    op.drop_table('sponsor_photo')
    op.drop_table('judge')
    op.drop_table('school')
    op.drop_table('project')
    op.drop_table('mentor_photo')
    ### end Alembic commands ###
