"""empty message

Revision ID: 185eb614137e
Revises: 2714485b741d
Create Date: 2014-03-15 18:15:49.596368

"""

# revision identifiers, used by Alembic.
revision = '185eb614137e'
down_revision = '2714485b741d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('secondround', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'secondround')
    ### end Alembic commands ###
