"""empty message

Revision ID: 1bd4b4cc43ed
Revises: e1d1256bb22
Create Date: 2014-03-01 05:46:22.005276

"""

# revision identifiers, used by Alembic.
revision = '1bd4b4cc43ed'
down_revision = 'e1d1256bb22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
