"""empty message

Revision ID: 2761eac32437
Revises: 4aa51094443b
Create Date: 2014-02-25 00:36:00.747045

"""

# revision identifiers, used by Alembic.
revision = '2761eac32437'
down_revision = '4aa51094443b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('innovation', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('plan', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('research', sa.Float(), nullable=True))
    op.drop_column('score', 'weighted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('weighted', mysql.FLOAT(), nullable=True))
    op.drop_column('score', 'research')
    op.drop_column('score', 'plan')
    op.drop_column('score', 'innovation')
    ### end Alembic commands ###
