"""empty message

Revision ID: 2c24bdbf26f2
Revises: 3f73643432b8
Create Date: 2015-01-02 11:28:26.759561

"""

# revision identifiers, used by Alembic.
revision = '2c24bdbf26f2'
down_revision = '3f73643432b8'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_winner', sa.Column('year', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_winner','year')
    ### end Alembic commands ###