"""empty message

Revision ID: 3b9a96729d42
Revises: a8dc2db25c4
Create Date: 2016-01-31 05:21:52.246836

"""

# revision identifiers, used by Alembic.
revision = '3b9a96729d42'
down_revision = 'a8dc2db25c4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge', sa.Column('cycle', sa.Integer(), nullable=True))
    op.drop_column('judge', 'specialcode')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge', sa.Column('specialcode', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('judge', 'cycle')
    ### end Alembic commands ###
