"""empty message

Revision ID: 49a0ea128c69
Revises: 4889a3e9dac5
Create Date: 2014-12-06 20:24:54.478417

"""

# revision identifiers, used by Alembic.
revision = '49a0ea128c69'
down_revision = '4889a3e9dac5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
