"""empty message

Revision ID: 4aa51094443b
Revises: 55967482f1e5
Create Date: 2014-02-04 21:15:15.301215

"""

# revision identifiers, used by Alembic.
revision = '4aa51094443b'
down_revision = '55967482f1e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('prize', sa.String(length=200), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsors')
    ### end Alembic commands ###
