"""empty message

Revision ID: 55967482f1e5
Revises: bfb04f92eba
Create Date: 2014-02-04 19:56:51.700815

"""

# revision identifiers, used by Alembic.
revision = '55967482f1e5'
down_revision = 'bfb04f92eba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequently_asked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('answer', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequently_asked')
    ### end Alembic commands ###
