"""empty message

Revision ID: 5d0a5822582
Revises: 1bd4b4cc43ed
Create Date: 2014-03-01 17:46:45.574121

"""

# revision identifiers, used by Alembic.
revision = '5d0a5822582'
down_revision = '1bd4b4cc43ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'firstround')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('firstround', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
