"""empty message

Revision ID: c687d53a10c
Revises: 12ae296935d5
Create Date: 2016-01-03 19:30:18.891535

"""

# revision identifiers, used by Alembic.
revision = 'c687d53a10c'
down_revision = '12ae296935d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
