"""empty message

Revision ID: e1d1256bb22
Revises: 151e96908d02
Create Date: 2014-03-01 05:22:43.278059

"""

# revision identifiers, used by Alembic.
revision = 'e1d1256bb22'
down_revision = '151e96908d02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('firstround', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'firstround')
    ### end Alembic commands ###
