"""empty message

Revision ID: e7b4fcdc65e
Revises: 93d2915723e
Create Date: 2014-03-28 00:51:51.777299

"""

# revision identifiers, used by Alembic.
revision = 'e7b4fcdc65e'
down_revision = '93d2915723e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_winner', sa.Column('year', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_winner','year')
    ### end Alembic commands ###
